import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { headers } from "next/headers";
import { redirect } from "next/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const headersList = headers().then(headers =>{
  //   console.log(headers);
  //   return headers
  // });


  headers().then((headersList) => {
    console.log(headersList);

    // const token = headersList.get('cookie')?.includes('token');
    const token = sessionStorage.getItem("token");

    if (!token) {
      redirect("/login");
    }
  });
  // const token = headersList.get('cookie')?.includes('token');

  // if (!token) {
  //   redirect('/login');
  // }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
